name: pocket-vep
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - pytorch
  - biopython
  - xgboost
  - requests
  - tqdm
  - pyarrow
  - pip
  - pip:
      - -e ..
